[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:5000 --workers 2 --threads 4 --timeout 120 wyzion_mem0_ai_demo.app.main:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
